image:
  file: .gitpod.Dockerfile
tasks:
  - name: Startup
    command: sh ./scripts/startup.sh
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - zhuangtongfa.material-theme
ports:
  - port: 1700
    onOpen: open-browser
  - port: 33060
    onOpen: ignore
  - port: 3306
    onOpen: ignore
